---

- name: Add {{ group }} group on {{ ansible_default_ipv4.address }}
  group:
    name: "{{ group }}"
    state: present
- name: Create {{ user }} user on {{ ansible_default_ipv4.address }}
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    groups: "{{ group }},adm"
    createhome: no
    shell: /bin/bash
    state: present
- name: Create {{ base_directory }} directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"


- name: Create sub-directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - filebeat
    - filebeat/config
    - filebeat/config/modules.d
    - filebeat/log
    - filebeat/data
  notify: restart_filebeat


- name: Get geoip pipeline
  uri:
    method: GET
    url: "https://{{ groups['elasticsearch'][0] }}:9200/_ingest/pipeline/geoip-info"
    validate_certs: no
    url_password: "{{ password }}"
    url_username: "elastic"
    return_content: yes
  failed_when: false
  register: elastic_geoip_pipeline
  changed_when: false

- name: Put geoip pipeline
  uri:
    method: PUT
    url: "https://{{ groups['elasticsearch'][0] }}:9200/_ingest/pipeline/geoip-info"
    validate_certs: no
    url_password: "{{ password }}"
    url_username: "elastic"
    body_format: json
    body: "{{ lookup('file', 'pipeline-geoip.json') }}"
  changed_when: false
  #when: >-


- name: Download filebeat for x86_64 with version {{ version }} on {{ ansible_default_ipv4.address }}
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ version }}-linux-x86_64.tar.gz"
    dest: "{{ base_directory }}/filebeat/filebeat-{{ version }}.tar.gz"
    force: yes
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: ansible_architecture == "x86_64"

- name: Extract filebeat on {{ ansible_default_ipv4.address }}
  unarchive:
    src: "{{ base_directory }}/filebeat/filebeat-{{ version }}.tar.gz"
    dest: "{{ base_directory }}/filebeat"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: yes
  notify: restart_filebeat

- name: Symlink for filebeat on {{ ansible_default_ipv4.address }}
  file:
    src: "{{ base_directory }}/filebeat/filebeat-{{ version }}-linux-x86_64"
    path: "{{ base_directory }}/filebeat/filebeat"
    state: link
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart_filebeat
  when: ansible_architecture == "x86_64"

- name: Configure general conf for filebeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/filebeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - filebeat.yml
    - modules.d/system.yml
  notify: restart_filebeat

- name: Configure elasticsearch for filebeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/filebeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - modules.d/elasticsearch.yml
  notify: restart_filebeat
  when: "'elasticsearch' in group_names"

- name: Configure kibana for filebeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/filebeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - modules.d/kibana.yml
  notify: restart_filebeat
  when: "'kibana' in group_names"


- name: Add Healthcheck script for filebeat on {{ ansible_default_ipv4.address }}
  template:
    src: "filebeat-healthcheck.sh.j2"
    dest: "{{ base_directory }}/filebeat/filebeat-healthcheck.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744
  notify: restart_filebeat

- name: Service systemD for filebeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/filebeat.service.j2
    dest: /etc/systemd/system/filebeat.service
    owner: root
    group: root
    mode: 0644
  notify: restart_filebeat
- name: Enable service filebeat
  systemd:
    enabled: yes
    daemon_reload: yes
    name: filebeat.service
...