---

# user/ group to run Elasticserach
user: elastic
group: elastic

base_directory: /elk
version: 7.10.2
clusterName: elk

heap: 254m

network_host: 0.0.0.0

password: test

# Required version of Java
java_version: 11

...
