---
# Install Kibana and Elasticserach
# Elasticsearch is private (listen on localhost)
# Kibana is private (listen on localhost and base path is /kibana)
# Kibana need a reverse proxy to be exposed such as nginx

- hosts: all
  vars_prompt:
    - name: password
      prompt: elasticsearch password
  tasks:
    - set_fact: password={{ password }}
      no_log: true

- name: Install elasticsearch
  hosts: elasticsearch
  roles:
    - role: elasticsearch
      tags: elasticsearch
      vars:
        - network_host: "localhost"
        - heap: 8g
        - version: 7.13.3


- name: Install kibana
  hosts: kibana
  roles:
    - role: kibana
      tags: kibana
      vars:
        - expose_on_localhost: "yes"
        - server_basepath: "/kibana"
        - version: 7.10.2
...
