---

- name: restart metricbeat
  systemd:
    state: restarted
    daemon_reload: yes
    name: metricbeat.service
  listen: restart_metricbeat

    
- name: Wait for metricbeat to be OK
  command: "{{ base_directory }}/metricbeat/metricbeat-healthcheck.sh"
  register: result
  until: result.rc == 0
  retries: 10
  delay: 20
  listen: restart_metricbeat

  
...
