---

- name: Add {{ group }} group
  group:
    name: "{{ group }}"
    state: present
- name: Create {{ user }} user
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    createhome: no
    shell: /bin/bash
    state: present
- name: Create {{ base_directory }} directory
  file:
    path: "{{ base_directory }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"


- name: Create sub-directory
  file:
    path: "{{ base_directory }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - auditbeat
    - auditbeat/config
    - auditbeat/config/audit.rules.d
    - auditbeat/data
  notify: restart_auditbeat

- name: Create log directory
  file:
    path: "/var/log/auditbeat"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart_auditbeat

- name: Get geoip pipeline
  uri:
    method: GET
    url: "https://{{ groups['elasticsearch'][0] }}:9200/_ingest/pipeline/geoip-info"
    validate_certs: no
    url_password: "{{ password }}"
    url_username: "elastic"
    return_content: yes
  failed_when: false
  register: elastic_geoip_pipeline
  changed_when: false

- name: Put geoip pipeline
  uri:
    method: PUT
    url: "https://{{ groups['elasticsearch'][0] }}:9200/_ingest/pipeline/geoip-info"
    validate_certs: no
    url_password: "{{ password }}"
    url_username: "elastic"
    body_format: json
    body: "{{ lookup('file', 'pipeline-geoip.json') }}"
  changed_when: false
  #when: >-

- name: Download auditbeat for x86_64 in version {{ version }}
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-{{ version }}-linux-x86_64.tar.gz"
    dest: "{{ base_directory }}/auditbeat/auditbeat-{{ version }}.tar.gz"
    force: yes
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: ansible_architecture == "x86_64"

- name: Download auditbeat for aarch64 with version {{ version }}
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-{{ version }}-linux-arm64.tar.gz"
    dest: "{{ base_directory }}/auditbeat/auditbeat-{{ version }}.tar.gz"
    force: yes
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: ansible_architecture == "aarch64"

- name: Extract auditbeat
  unarchive:
    src: "{{ base_directory }}/auditbeat/auditbeat-{{ version }}.tar.gz"
    dest: "{{ base_directory }}/auditbeat"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: yes
  notify: restart_auditbeat

- name: Retrieve directory name after extraction of the archive
  shell:
    cmd: "ls -d {{ base_directory }}/auditbeat/auditbeat-{{ version }}*/ | sed 's/.$//'"
  register: directory_name
  changed_when: false

- name: Symlink for auditbeat
  file:
    src: "{{ directory_name.stdout }}"
    path: "{{ base_directory }}/auditbeat/auditbeat"
    state: link
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart_auditbeat

- name: Configure general conf for auditbeat
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/auditbeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - auditbeat.yml
    - audit.rules.d/sample-rules.conf
  notify: restart_auditbeat


- name: Add Healthcheck script for auditbeat
  template:
    src: "auditbeat-healthcheck.sh.j2"
    dest: "{{ base_directory }}/auditbeat/auditbeat-healthcheck.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744
  notify: restart_auditbeat

- name: Service systemD for auditbeat
  template:
    src: templates/auditbeat.service.j2
    dest: /etc/systemd/system/auditbeat.service
    owner: root
    group: root
    mode: 0644
  notify: restart_auditbeat
- name: Enable service auditbeat
  systemd:
    enabled: yes
    daemon_reload: yes
    name: auditbeat.service
...