---

- name: Add {{ group }} group on {{ ansible_default_ipv4.address }}
  group:
    name: "{{ group }}"
    state: present
- name: Create {{ user }} user on {{ ansible_default_ipv4.address }}
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    createhome: no
    shell: /bin/bash
    state: present
- name: Create {{ base_directory }} directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"


- name: Create {{ item }} directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - auditbeat
    - auditbeat/config
    - auditbeat/config/audit.rules.d
    - auditbeat/log
    - auditbeat/data
  notify: restart_auditbeat

- name: Download auditbeat for x86_64
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-{{ version }}-linux-x86_64.tar.gz"
    dest: "{{ base_directory }}/auditbeat/auditbeat-{{ version }}.tar.gz"
    force: yes
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: ansible_architecture == "x86_64"

- name: Extract auditbeat on {{ ansible_default_ipv4.address }}
  unarchive:
    src: "{{ base_directory }}/auditbeat/auditbeat-{{ version }}.tar.gz"
    dest: "{{ base_directory }}/auditbeat"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: yes
  notify: restart_auditbeat

- name: Symlink for auditbeat on {{ ansible_default_ipv4.address }}
  file:
    src: "{{ base_directory }}/auditbeat/auditbeat-{{ version }}-linux-x86_64"
    path: "{{ base_directory }}/auditbeat/auditbeat"
    state: link
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart_auditbeat
  when: ansible_architecture == "x86_64"

- name: Configure general conf for auditbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/auditbeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - auditbeat.yml
    - audit.rules.d/sample-rules.conf
  notify: restart_auditbeat


- name: Add Healthcheck script for auditbeat on {{ ansible_default_ipv4.address }}
  template:
    src: "auditbeat-healthcheck.sh.j2"
    dest: "{{ base_directory }}/auditbeat/auditbeat-healthcheck.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744
  notify: restart_auditbeat

- name: Service systemD for auditbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/auditbeat.service.j2
    dest: /etc/systemd/system/auditbeat.service
    owner: root
    group: root
    mode: 0644
  notify: restart_auditbeat
- name: Enable service auditbeat
  systemd:
    enabled: yes
    daemon_reload: yes
    name: auditbeat.service
...