---

- name: Add {{ group }} group on {{ ansible_default_ipv4.address }}
  group:
    name: "{{ group }}"
    state: present
- name: Create {{ user }} user on {{ ansible_default_ipv4.address }}
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    groups: "{{ group }}"
    createhome: no
    shell: /bin/bash
    state: present
- name: Create {{ base_directory }} directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"


- name: Create {{ item }} directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - packetbeat
    - packetbeat/config
    - packetbeat/log
    - packetbeat/data
  notify: restart_packetbeat

- name: Download packetbeat for x86_64
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-{{ version }}-linux-x86_64.tar.gz"
    dest: "{{ base_directory }}/packetbeat/packetbeat-{{ version }}.tar.gz"
    force: yes
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: ansible_architecture == "x86_64"

- name: Extract packetbeat on {{ ansible_default_ipv4.address }}
  unarchive:
    src: "{{ base_directory }}/packetbeat/packetbeat-{{ version }}.tar.gz"
    dest: "{{ base_directory }}/packetbeat"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: yes
  notify: restart_packetbeat

- name: Symlink for packetbeat on {{ ansible_default_ipv4.address }}
  file:
    src: "{{ base_directory }}/packetbeat/packetbeat-{{ version }}-linux-x86_64"
    path: "{{ base_directory }}/packetbeat/packetbeat"
    state: link
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart_packetbeat
  when: ansible_architecture == "x86_64"

- name: Configure general conf for packetbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/packetbeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - packetbeat.yml
  notify: restart_packetbeat


- name: Add Healthcheck script for packetbeat on {{ ansible_default_ipv4.address }}
  template:
    src: "packetbeat-healthcheck.sh.j2"
    dest: "{{ base_directory }}/packetbeat/packetbeat-healthcheck.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744
  notify: restart_packetbeat

- name: Service systemD for packetbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/packetbeat.service.j2
    dest: /etc/systemd/system/packetbeat.service
    owner: root
    group: root
    mode: 0644
  notify: restart_packetbeat
- name: Enable service packetbeat
  systemd:
    enabled: yes
    daemon_reload: yes
    name: packetbeat.service
...