---

- name: Add {{ group }} group on {{ ansible_default_ipv4.address }}
  group:
    name: "{{ group }}"
    state: present
- name: Create {{ user }} user on {{ ansible_default_ipv4.address }}
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    createhome: no
    shell: /bin/bash
    state: present
- name: Create {{ base_directory }} directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"


- name: Create {{ item }} directory on {{ ansible_default_ipv4.address }}
  file:
    path: "{{ base_directory }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - metricbeat
    - metricbeat/config
    - metricbeat/config/modules.d
    - metricbeat/log
    - metricbeat/data
  notify: restart_metricbeat

- name: Download metricbeat for x86_64
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ version }}-linux-x86_64.tar.gz"
    dest: "{{ base_directory }}/metricbeat/metricbeat-{{ version }}.tar.gz"
    force: yes
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: ansible_architecture == "x86_64"

- name: Extract metricbeat on {{ ansible_default_ipv4.address }}
  unarchive:
    src: "{{ base_directory }}/metricbeat/metricbeat-{{ version }}.tar.gz"
    dest: "{{ base_directory }}/metricbeat"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: yes
  notify: restart_metricbeat

- name: Symlink for metricbeat on {{ ansible_default_ipv4.address }}
  file:
    src: "{{ base_directory }}/metricbeat/metricbeat-{{ version }}-linux-x86_64"
    path: "{{ base_directory }}/metricbeat/metricbeat"
    state: link
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
  notify: restart_metricbeat
  when: ansible_architecture == "x86_64"

- name: Configure general conf for metricbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/metricbeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - metricbeat.yml
    - modules.d/system.yml
  notify: restart_metricbeat

- name: Configure elasticsearch for metricbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/metricbeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - modules.d/elasticsearch-xpack.yml
  notify: restart_metricbeat
  when: "'elasticsearch' in group_names"

- name: Configure kibana for metricbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/{{ item }}.j2
    dest: "{{ base_directory }}/metricbeat/config/{{ item }}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  with_items:
    - modules.d/kibana-xpack.yml
  notify: restart_metricbeat
  when: "'kibana' in group_names"


- name: Add Healthcheck script for metricbeat on {{ ansible_default_ipv4.address }}
  template:
    src: "metricbeat-healthcheck.sh.j2"
    dest: "{{ base_directory }}/metricbeat/metricbeat-healthcheck.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744
  notify: restart_metricbeat

- name: Service systemD for metricbeat on {{ ansible_default_ipv4.address }}
  template:
    src: templates/metricbeat.service.j2
    dest: /etc/systemd/system/metricbeat.service
    owner: root
    group: root
    mode: 0644
  notify: restart_metricbeat
- name: Enable service metricbeat
  systemd:
    enabled: yes
    daemon_reload: yes
    name: metricbeat.service
...